name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: Backend
        file: Backend/Dockerfile
        push: true
        tags: |
          ali0707/fitnessapp-backend:latest
          ali0707/fitnessapp-backend:${{ github.sha }}

    - name: Build and push FrontUser Docker image
      uses: docker/build-push-action@v2
      with:
        context: FrontUser
        file: FrontUser/Dockerfile
        push: true
        tags: |
          ali0707/fitnessapp-frontuser:latest
          ali0707/fitnessapp-frontuser:${{ github.sha }}
