name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

   build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Backend Docker Image
      working-directory: FitnessApp/Backend
      run: |
        docker build -t ali0707/backend-image:latest .
        docker push ali0707/backend-image:latest

    - name: Build and Push FrontUser Docker Image
      working-directory: FitnessApp/FrontUser
      run: |
        docker build -t ali0707/frontuser-image:latest .
        docker push ali0707/frontuser-image:latest

