name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    

    - name: Setup Node.js environment and build react app
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies and build react app
      run: |
        npm install
        npm run build
      working-directory: FrontUser

    - name: Save version
      id: version
      run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
      working-directory: FrontUser

    - name: Increase version
      run: npm version patch

    - name: Push new version
      run: git push

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


    - name: Build and push FrontUser Docker image
      uses: docker/build-push-action@v2
      with:
        context: FrontUser
        file: FrontUser/Dockerfile
        push: true
        tags: |
          ali0707/fitnessapp-frontuser:latest
          ali0707/fitnessapp-frontuser:${{ github.sha }}
